import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { ApolloQueryResult, useQuery } from '@apollo/client';
import { getServerSideApolloProps } from '../../lib/apollo';
import { USER_QUERY } from '../../gql';
import { UserQuery, UserQueryVariables } from '../../types/generated';
import styles from '../../styles/Home.module.css'

interface ProfilePageProps {
  userId: number;
}

const ProfilePage: NextPage<ProfilePageProps> = ({ userId }) => {
  const { data } = useQuery<UserQuery, UserQueryVariables>(USER_QUERY, {
    variables: { id: userId }
  });

  const user = data?.user;

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/example/public/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/">
          <a className={styles.card}>Back to Users</a>
        </Link>

        {user && (
          <div className={styles.grid}>
            <div className={styles.card}>
              <div className={styles.cardImageContainer}>
                <Image src={user.img} objectFit="cover" layout="fill" />
              </div>
              <h2>{user.firstName} {user.lastName}</h2>
              <div className={styles.cardUserInfo}>
                <strong>Username</strong>
                <p>{user.username}</p>
              </div>
              <div className={styles.cardUserInfo}>
                <strong>Email</strong>
                <p>{user.email}</p>
              </div>
              <div className={styles.cardUserInfo}>
                <strong>Phone</strong>
                <p>{user.phone}</p>
              </div>
            </div>
          </div>
        )}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export const getServerSideProps = getServerSideApolloProps<ProfilePageProps>({
  hydrateQueries: ['user'],
  onHydrationComplete: ({ results }) => {
    const result: ApolloQueryResult<UserQuery> | undefined = results?.find(result => result.data.user);

    if (!result?.data.user) {
      return {
        redirect: {
          destination: '/?addUser=true',
          permanent: false,
        }
      }
    }

    return {
      props: {
        userId: Number(result.data.user.id),
      }
    }
  }
})

export default ProfilePage
